general {
    lock_cmd = ~/.config/hypr/scripts/lock.sh
    unlock_cmd = pkill hyprlock
}

listener {
    timeout = 300
    on-timeout = ~/.config/hypr/scripts/lock.sh
    on-resume = pkill hyprlock
}
